// Build PG design tokens from the single DTCG source (tokens/*.json) into:
//   dist/tokens.css  — CSS custom properties for the Astro/CSS marketing site (T1.3)
//   dist/theme.ts    — typed TS object for MUI createTheme in the portals/field app
// One source of truth → both surfaces (Command 5 §B). MUI never on the marketing site.
import StyleDictionary from 'style-dictionary';

const CSS_PREFIX = 'pg';

/** Build a value-only nested object from platform-transformed tokens (for the TS theme). */
function nestedValues(allTokens) {
  const root = {};
  for (const token of allTokens) {
    const value = token.$value ?? token.value;
    const flat = Array.isArray(value) ? value.join(', ') : value;
    let node = root;
    token.path.forEach((seg, i) => {
      if (i === token.path.length - 1) {
        node[seg] = flat;
      } else {
        node[seg] ??= {};
        node = node[seg];
      }
    });
  }
  return root;
}

StyleDictionary.registerFormat({
  name: 'pg/typescript-theme',
  format: ({ dictionary }) => {
    const obj = JSON.stringify(nestedValues(dictionary.allTokens), null, 2);
    return [
      '// AUTO-GENERATED by build-tokens.mjs — do not edit by hand.',
      '// Source: packages/tokens/tokens/*.json (DTCG). Rebuild: pnpm --filter @pg/tokens build',
      `export const tokens = ${obj} as const;`,
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      prefix: CSS_PREFIX,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [{ destination: 'theme.ts', format: 'pg/typescript-theme' }],
    },
  },
});

await sd.buildAllPlatforms();
console.log('✓ @pg/tokens built: dist/tokens.css + dist/theme.ts');
